name: Docker Image for SBI toolkit

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push image to ghcr
        run: |
          docker login --username turnmanh --password ${{  secrets.GHTOKEN }} ghcr.io
          docker build . -t ghcr.io/turnmanh/vscode-remote-image:latest
          docker push ghcr.io/turnmanh/vscode-remote-image:latest
  